### PR TITLE
Integer Byte Casting

### PR DESCRIPTION
**Pull request by dimitribouniol**
Rather than implementing integer bit flips ourselves, we should lean on the standard library and just interpret the bytes directly.

### Depends on:
- #58

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]

**Comment by dimitribouniol** [comment]
@swift-server-bot test this please

**Comment by 0xTim** [comment]
@swift-server-bot please test

**Comment by 0xTim** [comment]
@dimitribouniol you might need to push an empty commit or merge `main` to trigger CI

**Comment by 0xTim** [comment]
@swift-server-bot add to allowlist

**Pull request merged**
